#--------------------------------------------------
# Simple macro to generate 10^5 events
#
#/ROOT/setOutputFile root/study2a_betaX_dppFlat_coll1XXXX_Gr10mm_e5.root
#/ROOT/setOutputFile root/study2a_betaX_dppFlat_coll1XXXX_Al09mm_e5.root
#/ROOT/setOutputFile root/study2a_betaX_dppFlat_coll1XXXX_Cu03mm_e5.root
#
#/ROOT/setOutputFile root/study2b_betaX_dppFlat_coll1XXXX_Gr20000um_e5.root
 /ROOT/setOutputFile root/study2b_betaX_dppFlat_coll1XXXX_Al09210um_e5.root
#/ROOT/setOutputFile root/study2b_betaX_dppFlat_coll1XXXX_Cu01487um_e5.root
#
#--------------------------------------------------
/run/beamOn 100000
exit
